apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webhook-listener.fullname" . }}
  labels:
    {{- include "webhook-listener.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ .Values.config | toYaml | nindent 4 }}
