apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webhook-listener.fullname" . }}
  labels:
    {{- include "webhook-listener.labels" . | nindent 4 }}
data:
  config.yaml: |-
    common:
      log:
        level: {{ .Values.log.level | quote }}
        file: {{ .Values.log.file | quote }}
        format: {{ .Values.log.format | quote }}
    webhook:
      workers: {{ .Values.webhook.workers }}
      routes: {{ .Values.webhook.routes | toYaml | nindent 8 }}
    launcher:
      imageName: {{ .Values.launcher.imageName | quote }}
      pullPolicy: {{ .Values.launcher.pullPolicy | quote }}
      tag: {{ .Values.launcher.tag | quote }}
      namespace: {{ .Values.launcher.namespace | quote }}
      jobNamePrefix: {{ .Values.launcher.jobNamePrefix | quote }}
      timeout: {{ .Values.launcher.timeout }}
      gitSecret: {{ .Values.launcher.gitSecret | quote }}