apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webhook-listener.fullname" . }}
  labels:
    {{- include "webhook-listener.labels" . | nindent 4 }}
data:
  config.yaml: |-
    common:
      log:
        level: {{ .Values.config.common.log.level | quote }}
        file: {{ .Values.config.common.log.file | quote }}
        format: {{ .Values.config.common.log.format | quote }}
    webhook:
      workers: {{ .Values.config.webhook.workers }}
      routes: {{ .Values.config.webhook.routes | toYaml | nindent 8 }}
    launcher:
      imageName: {{ .Values.config.launcher.imageName | quote }}
      pullPolicy: {{ .Values.config.launcher.pullPolicy | quote }}
      tag: {{ .Values.config.launcher.tag | quote }}
      namespace: {{ .Values.config.launcher.namespace | quote }}
      jobNamePrefix: {{ .Values.config.launcher.jobNamePrefix | quote }}
      timeout: {{ .Values.config.launcher.timeout }}
      configmapName: {{ include "webhook-listener.fullname" . }}
      gitSecret: {{ .Values.config.launcher.gitSecret | quote }}
      cloneDepth: {{ .Values.config.launcher.cloneDepth }}
