apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.pipe-manager.org
spec:
  group: pipe-manager.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  nullable: true
                  type: string
                description:
                  type: string
                  nullable: true
                namespace:
                  type: object
                  nullable: true
                  properties:
                    name:
                      type: string
                      nullable: true
                    labels:
                      type: object
                      nullable: true
                      additionalProperties:
                        nullable: true
                        type: string
                sshSecretName:
                  type: string
                  nullable: true
                cloneDepth:
                  type: integer
                  nullable: true
                params:
                  type: object
                  nullable: true
                  additionalProperties:
                    nullable: true
                    type: string
                cloneRepository:
                  nullable: true
                  type: object
                  properties:
                    enable:
                      nullable: true
                      type: boolean
                    options:
                      nullable: true
                      type: object
                      properties:
                        artifacts:
                          nullable: true
                          type: boolean
                        cache:
                          nullable: true
                          type: boolean
                workspaceDir:
                  nullable: true
                  type: object
                launch:
                  nullable: true
                  type: object
                  properties:
                    whenFail:
                      type: array
                      nullable: true
                      items:
                        type: string
                        nullable: true
                    whenSuccess:
                      type: array
                      nullable: true
                      items:
                        type: string
                        nullable: true
                tasks:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      description:
                        type: string
                      runAfter:
                        type: array
                        nullable: true
                        items:
                          type: string
                      batch:
                        type: object
                        nullable: true
                        additionalProperties:
                          type: object
                          additionalProperties:
                            type: string
                      params:
                        type: object
                        nullable: true
                        additionalProperties:
                          type: string
                      cloneRepository:
                        nullable: true
                        type: object
                        properties:
                          enable:
                            type: boolean
                          options:
                            nullable: true
                            type: object
                            properties:
                              artifacts:
                                nullable: true
                                type: boolean
                              cache:
                                nullable: true
                                type: boolean
                      paths:
                        nullable: true
                        type: object
                        properties:
                          artifacts:
                            nullable: true
                            type: array
                            items:
                              type: string
                          cache:
                            nullable: true
                            type: array
                            items:
                              type: string
                      cloneDepth:
                        type: integer
                        nullable: true
                      steps:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            image:
                              type: string
                            description:
                              type: string
                              nullable: true
                            volumeMounts:
                              type: array
                              nullable: true
                              items:
                                type: object
                                additionalProperties: true
                            env:
                              type: array
                              nullable: true
                              items:
                                type: object
                                additionalProperties: true
                            script:
                              nullable: true
                              type: string
                      sidecars:
                        type: array
                        nullable: true
                        items:
                          type: object
                          additionalProperties: true
                      volumes:
                        type: array
                        nullable: true
                        items:
                          type: object
                          additionalProperties: true
                finishTasks:
                  type: object
                  nullable: true
                  properties:
                    fail:
                      type: object
                      nullable: true
                      additionalProperties:
                        type: object
                        properties:
                          description:
                            type: string
                            nullable: true
                          runAfter:
                            type: array
                            nullable: true
                            items:
                              type: string
                          batch:
                            type: object
                            nullable: true
                            additionalProperties:
                              type: object
                              additionalProperties:
                                type: string
                          params:
                            type: object
                            nullable: true
                            additionalProperties:
                              type: string
                          cloneRepository:
                            type: object
                            nullable: true
                            properties:
                              enable:
                                type: boolean
                              options:
                                type: object
                                nullable: true
                                properties:
                                  artifacts:
                                    type: boolean
                                    nullable: true
                                  cache:
                                    type: boolean
                                    nullable: true
                          paths:
                            type: object
                            nullable: true
                            properties:
                              artifacts:
                                type: array
                                nullable: true
                                items:
                                  type: string
                              cache:
                                type: array
                                nullable: true
                                items:
                                  type: string
                          cloneDepth:
                            type: integer
                            nullable: true
                          steps:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                image:
                                  type: string
                                description:
                                  type: string
                                  nullable: true
                                volumeMounts:
                                  type: array
                                  nullable: true
                                  items:
                                    type: object
                                    additionalProperties: true
                                env:
                                  type: array
                                  nullable: true
                                  items:
                                    type: object
                                    additionalProperties: true
                                script:
                                  type: string
                                  nullable: true
                          sidecars:
                            type: array
                            nullable: true
                            items:
                              type: object
                              additionalProperties: true
                          volumes:
                            type: array
                            nullable: true
                            items:
                              type: object
                              additionalProperties: true
                    success:
                      type: object
                      nullable: true
                      additionalProperties:
                        type: object
                        properties:
                          description:
                            type: string
                            nullable: true
                          runAfter:
                            type: array
                            nullable: true
                            items:
                              type: string
                          batch:
                            type: object
                            nullable: true
                            additionalProperties:
                              type: object
                              additionalProperties:
                                type: string
                          params:
                            type: object
                            nullable: true
                            additionalProperties:
                              type: string
                          cloneRepository:
                            type: object
                            nullable: true
                            properties:
                              enable:
                                type: boolean
                              options:
                                type: object
                                nullable: true
                                properties:
                                  artifacts:
                                    type: boolean
                                    nullable: true
                                  cache:
                                    type: boolean
                                    nullable: true
                          paths:
                            type: object
                            nullable: true
                            properties:
                              artifacts:
                                type: array
                                nullable: true
                                items:
                                  type: string
                              cache:
                                type: array
                                nullable: true
                                items:
                                  type: string
                          cloneDepth:
                            type: integer
                            nullable: true
                          steps:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                image:
                                  type: string
                                description:
                                  type: string
                                  nullable: true
                                volumeMounts:
                                  type: array
                                  nullable: true
                                  items:
                                    type: object
                                    additionalProperties: true
                                env:
                                  type: array
                                  nullable: true
                                  items:
                                    type: object
                                    additionalProperties: true
                                script:
                                  type: string
                                  nullable: true
                          sidecars:
                            type: array
                            nullable: true
                            items:
                              type: object
                              additionalProperties: true
                          volumes:
                            type: array
                            nullable: true
                            items:
                              type: object
                              additionalProperties: true
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: pipelines
    singular: pipeline
    kind: Pipeline
    shortNames:
      - pm
