apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.pipe-manager.sergiotejon.github.com
spec:
  group: pipe-manager.sergiotejon.github.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                  nullable: true
                namespace:
                  type: object
                  properties:
                    name:
                      type: string
                    labels:
                      type: object
                      nullable: true
                      additionalProperties:
                        type: string
                sshSecretName:
                  type: string
                  nullable: true
                params:
                  type: object
                  nullable: true
                  additionalProperties:
                    type: string
                tasks:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      description:
                        type: string
                      params:
                        type: object
                        nullable: true
                        additionalProperties:
                          type: string
                      steps:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            image:
                              type: string
                            description:
                              type: string
                              nullable: true
                            volumeMounts:
                              type: array
                              nullable: true
                              items:
                                type: object
                                additionalProperties: true
                            env:
                              type: array
                              nullable: true
                              items:
                                type: object
                                additionalProperties: true
                            script:
                              nullable: true
                              type: string
                      sidecars:
                        type: array
                        nullable: true
                        items:
                          type: object
                          additionalProperties: true
                      volumes:
                        type: array
                        nullable: true
                        items:
                          type: object
                          additionalProperties: true
                      runAfter:
                        type: array
                        nullable: true
                        items:
                          type: string
                finishTasks:
                  type: object
                  nullable: true
                  properties:
                    fail:
                      type: object
                      nullable: true
                      additionalProperties:
                        type: object
                        properties:
                          description:
                            nullable: true
                            type: string
                          steps:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                image:
                                  type: string
                                description:
                                  nullable: true
                                  type: string
                                script:
                                  nullable: true
                                  type: string
                          volumes:
                            type: array
                            nullable: true
                            items:
                              type: object
                              additionalProperties: true
                    success:
                      type: object
                      nullable: true
                      additionalProperties:
                        type: object
                        properties:
                          description:
                            nullable: true
                            type: string
                          steps:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                image:
                                  type: string
                                description:
                                  nullable: true
                                  type: string
                                script:
                                  nullable: true
                                  type: string
                          volumes:
                            type: array
                            nullable: true
                            items:
                              type: object
                              additionalProperties: true
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: pipelines
    singular: pipeline
    kind: Pipeline
    shortNames:
      - pipe
